name: proximity_hash
description: Generate a set of geohashes that cover a circular or square area, given the center coordinates and the radius
version: 2.1.0
homepage: https://github.com/anovis/proximity_hash

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.17.5
